# Generated by Django 4.2.16 on 2024-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinguser',
            name='car_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parkinguser',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
